# Generated by Django 4.1.5 on 2023-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
