# Generated by Django 4.1.5 on 2023-02-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_places_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics/people')),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(null=True)),
            ],
        ),
    ]
